name: JMeter Performance Tests

on:
  push:
    branches:
      - master

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter

      - name: Prepare Directories
        run: |
          rm -rf results_task reports_html
          mkdir -p results_task reports_html

      - name: Run Load Test
        continue-on-error: true # Дозволяє йти далі, навіть якщо тест "впав"
        run: |
          ./jmeter/bin/jmeter -n \
            -t test-plans/load_test.jmx \
            -l results_task/load_results.jtl \
            -e \
            -o reports_html/load_report

      - name: Run Stress Test
        continue-on-error: true
        run: |
          ./jmeter/bin/jmeter -n \
            -t test-plans/Stress_Testing.jmx \
            -l results_task/stress_results.jtl \
            -e \
            -o reports_html/stress_report

      - name: Run Endurance Test
        continue-on-error: true
        run: |
          ./jmeter/bin/jmeter -n \
            -t test-plans/endurance_test.jmx \
            -l results_task/endurance_results.jtl \
            -e \
            -o reports_html/endurance_report

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        if: always() # Гарантує, що звіти будуть збережені за будь-яких умов
        with:
          name: jmeter-all-reports
          path: reports_html/